name: macos-armv7

on: push

jobs:
  linux:
    name: macos-armv7
    runs-on: macos-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: macos armv7
        run: |
          cd /usr/share/misc && ls 
          echo 'export PATH="/usr/share/misc:$PATH"' >> ~/.bash_profile
          echo 'export FLAGS_GETOPT_CMD="/usr/share/misc/getopt"' >> ~/.bash_profile
          . ~/.bash_profile         
      - name: test
        run: |
          getopt --test
          echo "$?"
