name: macos-x86

on: push

jobs:
  linux:
    name: macos-x86
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: macos x86 compilation
        run: |
          ./install.sh --target=macos-x86_64 -t 32
