name: macos-armv7

on: push

jobs:
  linux:
    name: macos-armv7
    runs-on: macos-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: macos armv7
        run: |
          ./install.sh --target=ios-armv7 -t 32
