name: macos-armv7

on: push

jobs:
  linux:
    name: macos-armv7
    runs-on: macos-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: macos armv7
        run: |
          brew install gnu-getopt  
          echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> /Users/runner/.bash_profile
          source /Users/runner/.bash_profile
          getopt --test
          echo $?
      - name: test
        run: |
          getopt --test
          echo "$?"
