name: macos-armv7

on: push

jobs:
  linux:
    name: macos-armv7
    runs-on: macos-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: macos armv7
        run: |
          cd /usr/local/opt && ls
      - name: test
        run: |
          getopt --test
          echo "$?"
