name: windows-x86-avx2
on: push
jobs:
  windows-vs2019:
    name: windows-x86-avx2
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: windows x86 avx2 compilation
        run: |
          wget
