name: windows-x86-avx2

on: push

jobs:
  linux:
    name: windows-x86-avx2
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: windows x86 avx2 compilation
        run: |
          ./install.sh --target=windows-x86_64_avx2 -t 32
